# =========================
# Everblush Theme
# =========================

# Background & Foreground
background              #141b1e
foreground              #dadada

# Selection
selection_background    #2d3437
selection_foreground    #dadada

# Cursor
cursor                  #dadada
cursor_text_color       #141b1e

# URL
url_color               #67b0e8

# Borders
active_border_color     #8ccf7e
inactive_border_color   #141b1e
bell_border_color       #e57474

# Titlebar
wayland_titlebar_color  system
macos_titlebar_color    system

# Tabs
active_tab_background   #141b1e
active_tab_foreground   #8ccf7e
inactive_tab_background #141b1e
inactive_tab_foreground #7a8478
tab_bar_background      #141b1e

# Marks
mark1_background        #8ccf7e
mark1_foreground        #141b1e

mark2_background        #67b0e8
mark2_foreground        #141b1e

mark3_background        #e5c76b
mark3_foreground        #141b1e

mark4_background        #e57474
mark4_foreground        #141b1e

# =========================
# ANSI Colors
# =========================

# Black
color0  #232a2d
color8  #4b5658

# Red
color1  #e57474
color9  #ef7d7d

# Green
color2  #8ccf7e
color10 #a8d895

# Yellow
color3  #e5c76b
color11 #f0d98d

# Blue
color4  #67b0e8
color12 #80c0f0

# Magenta
color5  #c47fd5
color13 #d09de0

# Cyan
color6  #6cbfbf
color14 #8dd5d5

# White
color7  #b3b9b8
color15 #dadada
