[global/wm]
margin-top = 0
margin-bottom = 0


[colors]
bg = #00000000
fg = #d3c6aa
mbg = #f8f5e4

red = #e67e80
green = #a7c080
yellow = #dbbc7f
blue = #7fbbb3
purple = #d699b6
cyan = #83c092
orange = #e69875
grey = #272e33
blue-gray = #2d353b


[bar/brenda]
monitor = ${env:MONITOR:}
monitor-strict = false
override-redirect = false

bottom = true
fixed-center = true

width = 98%
height = 24

offset-x = 1%
offset-y = 17

background = ${colors.bg}
foreground = ${colors.fg}

radius = 1

line-size = 2
line-color = ${colors.blue}

border-size = 1px
border-color = ${colors.bg}

padding = 1

module-margin-left = 0
module-margin-right = 0

font-0 = JetBrainsMono Nerd Font:style=Bold:size=9;2
font-1 = JetBrainsMono Nerd Font:size=10;3

; LEFT
modules-left = launcher bspwm sep cpu_icon cpu_graph sep memory_bar sep filesystem sep network

; CENTER
modules-center = date

; RIGHT
modules-right = spotify sep profile sep pulseaudio sep battery sep time sep tray

separator =
dim-value = 1.0

wm-restack = bspwm
enable-ipc = true

cursor-click = pointer
cursor-scroll =


[settings]
screenchange-reload = true
pseudo-transparency = false


[module/launcher]
type = custom/text

label = "󰣇 "
label-font = 2
label-padding = 1
label-foreground = ${colors.blue-gray}
label-background = ${colors.green}


[module/bspwm]
type = internal/bspwm

enable-click = true
enable-scroll = true
reverse-scroll = true
pin-workspaces = true
occupied-scroll = false

format = <label-state>
format-background = ${colors.mbg}
format-font = 2

label-focused = 󰮯
label-focused-padding = 1
label-focused-foreground = ${colors.orange}

label-occupied = 󰊠
label-occupied-padding = 1
label-occupied-foreground = ${colors.purple}

label-urgent = 󰊠
label-urgent-padding = 1
label-urgent-foreground = ${colors.purple}

label-empty = 󰑊
label-empty-padding = 1
label-empty-foreground = ${colors.blue-gray}


[module/sep]
type = custom/text

label = " "
label-foreground = ${colors.bg}


; =========================================================
; CPU
; =========================================================

[module/cpu_icon]
type = custom/text

label = " "
label-font = 2
label-padding = 1

label-background = ${colors.red}
label-foreground = ${colors.blue-gray}


[module/cpu_graph]
type = custom/script

exec = python -u ~/.config/polybar/scripts/cpu_graph.py
tail = true

format = <label>

label = %output%
label-background = ${colors.mbg}
label-foreground = ${colors.blue-gray}
label-padding = 1


; =========================================================
; MEMORY
; =========================================================

[module/memory_bar]
type = custom/script

exec = python -u ~/.config/polybar/scripts/memory_graph.py
tail = true

format = <label>

label = %output%
label-background = ${colors.mbg}
label-foreground = ${colors.blue-gray}
label-padding = 1


; =========================================================
; FILESYSTEM
; =========================================================

[module/filesystem]
type = internal/fs

mount-0 = /
interval = 30
fixed-values = true

format-mounted = <label-mounted>

format-mounted-prefix = " "
format-mounted-prefix-padding = 1
format-mounted-prefix-font = 2
format-mounted-prefix-background = ${colors.yellow}
format-mounted-prefix-foreground = ${colors.blue-gray}

label-mounted = "%percentage_used:3%%"
label-mounted-padding = 1
label-mounted-background = ${colors.mbg}
label-mounted-foreground = ${colors.blue-gray}

label-unmounted = "OFF"
label-unmounted-padding = 1
label-unmounted-background = ${colors.mbg}
label-unmounted-foreground = ${colors.blue-gray}


; =========================================================
; NETWORK
; =========================================================

[module/network]
type = custom/script

exec = python -u ~/.config/polybar/scripts/network.py
tail = true

format = <label>

label = %output%
label-background = ${colors.mbg}
label-foreground = ${colors.blue-gray}
label-padding = 1

click-left = kitty --title "Network Control" -e python ~/.config/polybar/scripts/network_cli.py


; =========================================================
; TIME
; =========================================================

[module/time]
type = internal/date

interval = 1

time = %I:%M %P

format = <label>

format-prefix = " "
format-prefix-padding = 1
format-prefix-font = 2
format-prefix-background = ${colors.blue}
format-prefix-foreground = ${colors.blue-gray}

label = "%time%"
label-padding = 1
label-background = ${colors.mbg}
label-foreground = ${colors.blue-gray}


; =========================================================
; DATE CENTER
; =========================================================

[module/date]
type = internal/date

interval = 10

date = %a, %d %b %Y

format = <label>

format-prefix = " "
format-prefix-padding = 1
format-prefix-font = 2
format-prefix-background = ${colors.green}
format-prefix-foreground = ${colors.blue-gray}

label = "%date%"
label-padding = 1
label-background = ${colors.mbg}
label-foreground = ${colors.blue-gray}


; =========================================================
; VOLUME
; =========================================================
[module/pulseaudio]
type = internal/pulseaudio

interval = 2
use-ui-max = true
reverse-scroll = true

; ==========================================
; NORMAL VOLUME
; ==========================================

format-volume = <ramp-volume><label-volume>

ramp-volume-0 = ""
ramp-volume-1 = ""
ramp-volume-2 = ""
ramp-volume-3 = ""
ramp-volume-4 = ""

ramp-volume-font = 2

ramp-volume-padding = 1
ramp-volume-background = ${colors.orange}
ramp-volume-foreground = ${colors.blue-gray}

; ==========================================
; PERCENTAGE
; ==========================================

label-volume = "%percentage:3%%"
label-volume-padding = 1
label-volume-background = ${colors.mbg}
label-volume-foreground = ${colors.blue-gray}

; ==========================================
; MUTED
; ==========================================

format-muted = <label-muted>

label-muted = " Mute"
label-muted-font = 2
label-muted-padding = 1

label-muted-background = ${colors.red}
label-muted-foreground = ${colors.blue-gray}

; ==========================================
; MOUSE
; ==========================================

click-left = pavucontrol


scroll-up = wpctl set-volume @DEFAULT_AUDIO_SINK@ 5%+
scroll-down = wpctl set-volume @DEFAULT_AUDIO_SINK@ 5%-
; =========================================================
; BATTERY
; =========================================================

[module/battery]
type = custom/script

exec = ~/.config/polybar/battery.sh
interval = 5

format = <label>

label = "%output%"
label-padding = 1
label-background = ${colors.mbg}
label-foreground = ${colors.blue-gray}


; =========================================================
; PROFILE
; =========================================================

[module/profile]
type = custom/text

label = " "
label-font = 2
label-padding = 1

label-foreground = ${colors.blue-gray}
label-background = ${colors.purple}

click-left = ~/.config/polybar/eww-dashboard.sh close
click-right = ~/.config/polybar/eww-dashboard.sh open


; =========================================================
; REAL SYSTEM TRAY
; =========================================================

[module/tray]
type = internal/tray

format = <tray>

format-background = ${colors.bg}
tray-foreground = ${colors.fg}

tray-spacing = 8px
tray-padding = 0px
tray-size = 70%


[module/spotify]
type = custom/script

exec = python ~/.config/polybar/scripts/spotify.py
tail = true

format = <label>

label = %output%
label-padding = 1
label-background = ${colors.mbg}
label-foreground = ${colors.blue-gray}

click-left = python ~/.config/polybar/scripts/spotify.py close
click-right = python ~/.config/polybar/scripts/spotify.py open
